{{- if not .Values.existingConfigSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "teldrive.configSecretName" . }}
  labels:
    {{- include "teldrive.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.existingConfigSecretKey | quote }}: |
    {{- include "teldrive.config" . | nindent 4 }}
{{- end }}
